In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas 

Target website:https://www.football-data.co.uk/data.php

In [3]:
# reading the csv file from the website
df_premier21=pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [6]:
#reanaming columns 
df_premier21.rename(columns={'FTHG':'Home_Goals','FTAG':'away_goals'},inplace=True)

In [9]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,Home_Goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

# Read .csv from Multiple URLs with pandas

-https://www.football-data.co.uk/mmz4281/2526/E0.csv

-https://www.football-data.co.uk/mmz4281/2526/E1.csv

Link:root+season+leauge

In [11]:
#link structure
"https://www.football-data.co.uk/mmz4281/"+"2526"+"/"+"E0"+".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [13]:
# Create root variable 
root ="https://www.football-data.co.uk/mmz4281/"

## Multiple leauges 
-https://www.football-data.co.uk/mmz4281/2526/E0.csv

-https://www.football-data.co.uk/mmz4281/2526/E1.csv

-https://www.football-data.co.uk/mmz4281/2526/E2.csv

-https://www.football-data.co.uk/mmz4281/2526/E3.csv

-https://www.football-data.co.uk/mmz4281/2526/E4.csv

In [16]:
# creating list of leauges 
leauges=['E0','E1','E2','E3','EC']
frames=[]

# looping thirough leauges, read multiple csv and append it into a list
for leauge in leauges:
    df=pd.read_csv(root +'2526' + '/' + leauge+ '.csv')
    frames.append(df)

In [17]:
# length of frames 
len(frames)

5

In [18]:
#show 1st,2nd and 3rd elemnt
frames[0]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

## Multiple seasons

In [21]:
# creating list of leauges 
leauges=['E0','E2','E3']
frames=[]

# loop through range of seasons and insert new column 
for leauge in leauges:
    for season in range(20,26):
        df=pd.read_csv(root + str(season) + str(season+1) + '/' + leauge+ '.csv')
        df.insert(1, 'season',season)
        frames.append(df)

In [26]:
#total frames(6 seasons x 3 leauges)
len(frames)

18

In [28]:
# show 1st, and last element (new season column was created)
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88,NaN
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93,NaN
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12,NaN
3,E3,25,02/08/2025,15:00,Cambridge,Cheltenham,1,0,H,0,...,1.88,1.88,1.97,1.98,1.88,1.90,1.83,1.98,2.00,NaN
4,E3,25,02/08/2025,15:00,Chesterfield,Barrow,1,0,H,1,...,2.03,1.79,2.06,1.80,2.07,1.73,2.02,1.87,2.13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,25,02/05/2026,15:00,Harrogate,Barnet,1,2,A,1,...,1.73,NaN,NaN,2.08,1.80,1.99,1.73,NaN,NaN,NaN
548,E3,25,02/05/2026,15:00,Notts County,Bristol Rvs,1,1,D,1,...,1.93,NaN,NaN,1.93,1.93,1.86,1.86,NaN,NaN,NaN
549,E3,25,02/05/2026,15:00,Oldham,Accrington,3,0,H,1,...,1.88,NaN,NaN,1.98,1.88,1.84,1.87,NaN,NaN,NaN
550,E3,25,02/05/2026,15:00,Swindon,Chesterfield,1,2,A,1,...,1.83,NaN,NaN,2.03,1.83,1.96,1.77,NaN,NaN,NaN
551,E3,25,02/05/2026,15:00,Tranmere,Grimsby,1,1,D,0,...,1.95,NaN,NaN,1.90,1.95,1.87,1.85,NaN,NaN,NaN

# Organize all the data in a dictionary

In [35]:
# create a dictionary with original names of leauge as key 
dict_countries={'Spanish La Liga':'SP1','Spanish Segunda Division':'SP2','German Bundesliga':'D1','English Premier Leauge':'E0','English Leauge 1':'E2','English leauge 2':'E3'}

In [40]:
for leauge in dict_countries:
    print(dict_countries[leauge])

SP1
SP2
D1
E0
E2
E3

In [50]:
dict_historical_data = {}
# creating list of leauges
#leauges['E0','E2','E3']

# loop through range of seasons and insert new column 
for leauge in dict_countries:
    frames=[]
    for season in range(20,26):
        df=pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[leauge]+ '.csv')
        df.insert(1, 'season',season)
        frames.append(df)
    df_concat = pd.concat(frames)    
    dict_historical_data[leauge] = df_concat

In [54]:
#show dataframe inside dict_historical_data
dict_historical_data['English Premier Leauge']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,...,6.75,1.4,5.25,7.00,1.40,5.25,6.00,1.40,5.25,6.00
376,E0,25,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,...,1.90,3.5,3.80,1.95,3.40,3.60,2.05,3.40,3.60,2.05
377,E0,25,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,...,1.96,3.4,3.70,2.05,3.40,3.60,2.05,3.40,3.50,2.05
378,E0,25,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,...,4.10,1.9,3.40,4.33,1.85,3.50,4.20,1.85,3.50,4.00
379,E0,25,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,...,4.35,1.7,4.10,4.50,1.73,4.20,4.33,1.70,4.00,4.20